"""Database package facade for SecAi repositories and connection lifecycle."""

from __future__ import annotations

import sqlite3

import psycopg

from secai.database._utils import utc_now
from secai.database.accounts_sites import (
    create_session,
    create_site,
    create_user,
    delete_session,
    delete_site,
    delete_user,
    ensure_judge_site,
    ensure_judge_user,
    get_site,
    get_user_by_email,
    get_user_by_session,
    list_sites,
    public_site_script_config,
    rotate_site_ingest_key,
    user_owns_site,
    verify_ingest_key,
)
from secai.database.analysis_qwen import (
    claim_next_analysis_job,
    create_analysis_job,
    get_analysis_job,
    get_analysis_job_for_event,
    insert_qwen_usage,
    list_analysis_jobs_for_site,
    list_qwen_usage_for_sites,
    requeue_stale_analysis_jobs,
    retry_analysis_job,
    summarize_qwen_usage_for_sites,
    update_analysis_job,
)
from secai.database.cloud_report_config import (
    connect_discord_setup_code,
    delete_alibaba_connection,
    get_alibaba_autopilot_config,
    list_alibaba_autopilot_configs_with_sls,
    list_report_channels,
    mark_alibaba_collector_error,
    mark_alibaba_connection_error,
    prepare_alibaba_connection,
    save_alibaba_autopilot_config,
    save_report_channel,
    verify_alibaba_collector,
    verify_alibaba_connection,
)
from secai.database.connection import close_database_pool, connect, database_backend, init_db
from secai.database.evidence import get_event, get_events, insert_event, recent_analysis_events, recent_events
from secai.database.incidents_decisions import (
    consume_approval_token,
    get_incident,
    get_incident_by_approval_token,
    insert_incident,
    list_approval_decisions,
    list_incidents,
    list_incidents_for_sites,
    record_approval_decision,
    transition_incident_status,
    update_incident_status,
)
from secai.database.policies_executions import (
    claim_due_policy,
    get_or_insert_policy,
    get_policies_for_incidents,
    get_policy,
    get_policy_for_incident,
    insert_policy,
    list_due_active_policies,
    list_policies,
    list_remediation_executions,
    reconcile_interrupted_actions,
    record_remediation_execution,
    transition_policy_status,
    update_policy_execution_state,
)

INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.IntegrityError)

__all__ = [
    "INTEGRITY_ERRORS",
    "claim_due_policy",
    "claim_next_analysis_job",
    "close_database_pool",
    "connect",
    "connect_discord_setup_code",
    "consume_approval_token",
    "create_analysis_job",
    "create_session",
    "create_site",
    "create_user",
    "database_backend",
    "delete_session",
    "delete_site",
    "delete_user",
    "delete_alibaba_connection",
    "ensure_judge_site",
    "ensure_judge_user",
    "get_alibaba_autopilot_config",
    "get_analysis_job",
    "get_analysis_job_for_event",
    "get_event",
    "get_events",
    "get_incident",
    "get_incident_by_approval_token",
    "get_or_insert_policy",
    "get_policies_for_incidents",
    "get_policy",
    "get_policy_for_incident",
    "get_site",
    "get_user_by_email",
    "get_user_by_session",
    "init_db",
    "insert_event",
    "insert_incident",
    "insert_policy",
    "insert_qwen_usage",
    "list_alibaba_autopilot_configs_with_sls",
    "list_analysis_jobs_for_site",
    "list_approval_decisions",
    "list_due_active_policies",
    "list_incidents",
    "list_incidents_for_sites",
    "list_policies",
    "list_qwen_usage_for_sites",
    "list_remediation_executions",
    "list_report_channels",
    "list_sites",
    "mark_alibaba_collector_error",
    "mark_alibaba_connection_error",
    "prepare_alibaba_connection",
    "public_site_script_config",
    "recent_analysis_events",
    "recent_events",
    "reconcile_interrupted_actions",
    "record_approval_decision",
    "record_remediation_execution",
    "requeue_stale_analysis_jobs",
    "retry_analysis_job",
    "rotate_site_ingest_key",
    "save_alibaba_autopilot_config",
    "save_report_channel",
    "summarize_qwen_usage_for_sites",
    "transition_incident_status",
    "transition_policy_status",
    "update_analysis_job",
    "update_incident_status",
    "update_policy_execution_state",
    "user_owns_site",
    "utc_now",
    "verify_ingest_key",
    "verify_alibaba_collector",
    "verify_alibaba_connection",
]
