from __future__ import annotations

from typing import Any

from secai.database.migrations import migrate


def initialize(conn: Any, database_path: str, schema_version: int) -> None:
    """Create the current SecAi schema or reject a database from another schema generation."""
    dialect = getattr(conn, "dialect", "sqlite")
    if dialect == "sqlite":
        if database_path not in (":memory:", ""):
            conn.execute("pragma journal_mode = WAL")
        table_query = "select name from sqlite_master where type = 'table' and name not like 'sqlite_%'"
    else:
        table_query = "select tablename as name from pg_tables where schemaname = current_schema()"
    existing_tables = {row["name"] for row in conn.execute(table_query).fetchall()}
    if existing_tables and "schema_metadata" not in existing_tables:
        raise RuntimeError("Unsupported pre-v1 SecAi database. Use an empty database with this release.")
    if "schema_metadata" in existing_tables:
        version_query = "select version from schema_metadata where singleton = 1"
        if dialect == "postgresql":
            version_query += " for update"
        version = conn.execute(version_query).fetchone()
        found = version["version"] if version else "missing"
        if not version:
            raise RuntimeError(
                f"Unsupported SecAi database schema {found}; this release requires schema {schema_version}."
            )
        migrate(conn, int(found), schema_version)
    schema_sql = SCHEMA_SQL
    if dialect == "postgresql":
        schema_sql = schema_sql.replace(
            "integer primary key autoincrement",
            "integer generated by default as identity primary key",
        )
        for statement in schema_sql.split(";"):
            if statement.strip():
                conn.execute(statement)
    else:
        conn.executescript(schema_sql)
    conn.execute(
        "insert into schema_metadata (singleton, version) values (1, ?) on conflict (singleton) do nothing",
        (schema_version,),
    )
    _create_indexes(conn)


SCHEMA_SQL = """
create table if not exists schema_metadata (
    singleton integer primary key check (singleton = 1),
    version integer not null
);

create table if not exists sites (
    site_id text primary key,
    name text not null,
    owner_email text,
    ingest_key text not null,
    evidence_source text not null,
    created_at text not null,
    check (evidence_source in ('browser', 'alibaba_autopilot'))
);

create table if not exists users (
    id integer primary key autoincrement,
    email text not null unique,
    password_hash text not null,
    created_at text not null
);

create table if not exists sessions (
    token text primary key,
    user_id integer not null,
    created_at text not null,
    expires_at text not null,
    foreign key (user_id) references users(id) on delete cascade
);

create table if not exists events (
    id integer primary key autoincrement,
    site_id text not null,
    source text not null,
    event_type text not null,
    event_fingerprint text,
    method text,
    path text,
    query text,
    status_code integer,
    ip text,
    user_agent text,
    payload text,
    signals_json text not null,
    metadata_json text not null,
    created_at text not null,
    foreign key (site_id) references sites(site_id) on delete cascade
);

create table if not exists incidents (
    id integer primary key autoincrement,
    site_id text not null,
    title text not null,
    severity text not null,
    status text not null,
    attack_type text not null,
    affected_route text,
    confidence real not null,
    report text not null,
    recommended_action_json text not null,
    created_at text not null,
    updated_at text not null,
    foreign key (site_id) references sites(site_id) on delete cascade,
    check (severity in ('low', 'medium', 'high', 'critical')),
    check (status in ('reported', 'needs_review', 'applying', 'approved', 'rejected'))
);

create table if not exists approval_tokens (
    incident_id integer primary key,
    token_hash text not null unique,
    expires_at text not null,
    consumed_at text,
    created_at text not null,
    foreign key (incident_id) references incidents(id) on delete cascade
);

create table if not exists approval_decisions (
    id integer primary key autoincrement,
    incident_id integer not null,
    site_id text not null,
    actor text not null,
    channel text not null,
    decision text not null check (decision in ('approved', 'rejected')),
    note text,
    previous_status text not null,
    resulting_status text not null,
    created_at text not null,
    foreign key (incident_id) references incidents(id) on delete cascade,
    foreign key (site_id) references sites(site_id) on delete cascade
);

create table if not exists policies (
    id integer primary key autoincrement,
    site_id text not null,
    action text not null,
    target text not null,
    reason text not null,
    incident_id integer,
    provider text,
    provider_rule_id text,
    parameters_json text not null default '{}',
    status text not null default 'pending',
    applied_at text,
    error_message text,
    expires_at text,
    created_at text not null,
    foreign key (site_id) references sites(site_id) on delete cascade,
    foreign key (incident_id) references incidents(id) on delete cascade,
    check (status in ('pending', 'applying', 'active', 'revoking', 'revoked', 'expired', 'failed'))
);

create table if not exists remediation_executions (
    id integer primary key autoincrement,
    site_id text not null,
    policy_id integer,
    incident_id integer,
    provider text not null,
    action text not null,
    target text not null,
    status text not null,
    request_json text not null,
    response_json text not null,
    error_message text,
    created_at text not null,
    foreign key (site_id) references sites(site_id) on delete cascade,
    foreign key (policy_id) references policies(id) on delete cascade,
    foreign key (incident_id) references incidents(id) on delete cascade
);

create table if not exists analysis_jobs (
    id integer primary key autoincrement,
    event_id integer not null,
    site_id text not null,
    status text not null,
    current_step text,
    error text,
    incident_id integer,
    attempt_count integer not null default 0,
    claimed_at text,
    created_at text not null,
    updated_at text not null,
    foreign key (event_id) references events(id) on delete cascade,
    foreign key (site_id) references sites(site_id) on delete cascade,
    foreign key (incident_id) references incidents(id) on delete set null
);

create table if not exists qwen_usage (
    id integer primary key autoincrement,
    job_id integer,
    event_id integer,
    incident_id integer,
    agent_name text not null,
    model text not null,
    input_tokens integer,
    output_tokens integer,
    total_tokens integer,
    model_calls integer not null default 1,
    latency_ms integer not null,
    error_message text,
    created_at text not null,
    foreign key (job_id) references analysis_jobs(id) on delete cascade,
    foreign key (event_id) references events(id) on delete cascade,
    foreign key (incident_id) references incidents(id) on delete set null
);

create table if not exists site_alibaba_autopilot_configs (
    site_id text primary key,
    role_arn text,
    external_id text not null unique,
    account_id text,
    connection_status text not null default 'pending',
    connection_error text,
    verified_at text,
    region text not null,
    security_group_id text,
    sls_endpoint text,
    sls_project text,
    sls_logstore text,
    ecs_instance_id text,
    collector_status text not null default 'not_configured',
    collector_error text,
    collector_machine_group text,
    collector_config_name text,
    collector_create_index integer not null default 0,
    collector_verified_at text,
    enforcement_mode text not null,
    created_at text not null,
    updated_at text not null,
    foreign key (site_id) references sites(site_id) on delete cascade,
    check (connection_status in ('pending', 'verified', 'error')),
    check (collector_status in ('not_configured', 'pending', 'verified', 'error'))
);

create table if not exists site_report_channels (
    site_id text not null,
    channel text not null,
    enabled integer not null,
    config_json text not null,
    created_at text not null,
    updated_at text not null,
    primary key (site_id, channel)
);

"""


def _create_indexes(conn: Any) -> None:
    conn.execute(
        """
        create unique index if not exists idx_events_site_fingerprint
        on events(site_id, event_fingerprint)
        where event_fingerprint is not null
        """
    )
    conn.execute("create index if not exists idx_events_site_id on events(site_id, id desc)")
    conn.execute("create index if not exists idx_incidents_site_id on incidents(site_id, id desc)")
    conn.execute("create index if not exists idx_analysis_jobs_event_id on analysis_jobs(event_id)")
    conn.execute("create index if not exists idx_analysis_jobs_status_id on analysis_jobs(status, id)")
    conn.execute("create index if not exists idx_analysis_jobs_site_id on analysis_jobs(site_id, id desc)")
    conn.execute(
        "create unique index if not exists idx_analysis_jobs_incident_id "
        "on analysis_jobs(incident_id) where incident_id is not null"
    )
    conn.execute("create index if not exists idx_sessions_expires_at on sessions(expires_at)")
    conn.execute(
        "create unique index if not exists idx_policies_incident on policies(incident_id) where incident_id is not null"
    )
    conn.execute("create index if not exists idx_policies_due on policies(status, expires_at)")
    conn.execute(
        "create index if not exists idx_approval_decisions_incident on approval_decisions(incident_id, id desc)"
    )
    conn.execute(
        "create unique index if not exists idx_alibaba_customer_role "
        "on site_alibaba_autopilot_configs(role_arn) where role_arn is not null"
    )
    conn.execute(
        "create unique index if not exists idx_alibaba_site_security_group "
        "on site_alibaba_autopilot_configs(account_id, region, security_group_id) "
        "where account_id is not null and security_group_id is not null"
    )
    conn.execute(
        "create unique index if not exists idx_alibaba_site_logstore "
        "on site_alibaba_autopilot_configs(account_id, sls_endpoint, sls_project, sls_logstore) "
        "where account_id is not null and sls_endpoint is not null "
        "and sls_project is not null and sls_logstore is not null"
    )
    conn.execute(
        "create unique index if not exists idx_alibaba_site_ecs_instance "
        "on site_alibaba_autopilot_configs(account_id, region, ecs_instance_id) "
        "where account_id is not null and ecs_instance_id is not null"
    )
