from __future__ import annotations

from typing import Any


def apply(conn: Any) -> None:
    """Add durable Qwen action jobs and link their model usage."""
    identity = (
        "integer generated by default as identity primary key"
        if getattr(conn, "dialect", "sqlite") == "postgresql"
        else "integer primary key autoincrement"
    )
    conn.execute(
        f"""
        create table action_jobs (
            id {identity},
            incident_id integer not null unique,
            site_id text not null,
            action text not null,
            tool_name text not null,
            requires_approval integer not null,
            approval_decision_id integer,
            status text not null,
            current_step text,
            attempt_count integer not null default 0,
            claimed_at text,
            result_json text not null default '{{}}',
            error text,
            created_at text not null,
            updated_at text not null,
            foreign key (incident_id) references incidents(id) on delete cascade,
            foreign key (site_id) references sites(site_id) on delete cascade,
            foreign key (approval_decision_id) references approval_decisions(id) on delete restrict,
            check (status in ('awaiting_approval', 'queued', 'running', 'succeeded', 'failed', 'rejected'))
        )
        """
    )
    conn.execute("create index idx_action_jobs_status_id on action_jobs(status, id)")
    conn.execute("create index idx_action_jobs_site_id on action_jobs(site_id, id desc)")
    conn.execute("alter table qwen_usage add column action_job_id integer references action_jobs(id) on delete cascade")
